### ISSUE TITLE
coc-stylelint service not starting 

### ISSUE THREAD

**Issue by dasraab** [neoclide/coc-stylelint#5]
getting this error when coc-stylelint is started. coc tries about 5 times to start coc-stylelint and finally gives up with following error:

```
309 SyntaxError: Unexpected token {
310     at createScript (vm.js:80:10)
311     at Object.runInThisContext (vm.js:139:10)
312     at Module._compile (module.js:617:28)
313     at Object.Module._extensions..js (module.js:664:10)
314     at Module.load (module.js:566:32)
315     at tryModuleLoad (module.js:506:12)
316     at Function.Module._load (module.js:498:3)
317     at Function.Module.runMain (module.js:694:10)
318     at startup (bootstrap_node.js:204:16)
319     at bootstrap_node.js:625:3
320
321 [Error  - 23:33:33] Connection to server got closed. Server will not be restarted.
````

Any hint on how i can fix this? Woud love to get this great extension running!

**Comment by chemzqm** [comment]
Looks like the installed coc-stylelint is broken.

**Comment by kjf** [comment]
This looks like the issue I reported to coc-prettier. https://github.com/neoclide/coc-prettier/issues/26
